# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
    # Schedule updates (daily)
    schedule: [{cron: "0 0 * * *"}]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: {branches: ["master", "main"]}
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - name: 🗃️ Base content
            uses: lowlighter/metrics@latest
            with:
                use_prebuilt_image: yes
                filename: metrics/metrics.base.svg
                token: ${{ secrets.METRICS_TOKEN }}
                plugins_errors_fatal: yes
                user: colding10
                template: classic
                config_timezone: America/Los_Angeles

                base: header, activity, community, repositories, metadata

          - name: 📅 Isometric commit calendar
            uses: lowlighter/metrics@latest
            with:
                use_prebuilt_image: yes
                filename: metrics/metrics.isocalendar.svg
                token: ${{ secrets.METRICS_TOKEN }}
                plugins_errors_fatal: yes
                user: colding10
                template: classic
                config_timezone: America/Los_Angeles

                base: ""
                plugin_isocalendar: yes
                plugin_isocalendar_duration: full-year

          - name: 🈷️ Languages activity
            uses: lowlighter/metrics@latest
            with:
                use_prebuilt_image: yes
                filename: metrics/metrics.languages.svg
                token: ${{ secrets.METRICS_TOKEN }}
                plugins_errors_fatal: yes
                user: colding10
                template: classic
                config_timezone: America/Los_Angeles

                base: ""
                plugin_languages: yes
                plugin_languages_analysis_timeout: 15
                plugin_languages_analysis_timeout_repositories: 7.5
                plugin_languages_categories: markup, programming
                plugin_languages_colors: github
                plugin_languages_limit: 8
                plugin_languages_recent_categories: markup, programming
                plugin_languages_recent_days: 14
                plugin_languages_recent_load: 300
                plugin_languages_sections: most-used
                plugin_languages_threshold: 0%

          - name: ✨ Stargazers
            uses: lowlighter/metrics@latest
            with:
                use_prebuilt_image: yes
                filename: metrics/metrics.stargazers.svg
                token: ${{ secrets.METRICS_TOKEN }}
                plugins_errors_fatal: yes
                user: colding10
                template: classic
                config_timezone: America/Los_Angeles

                base: ""
                plugin_stargazers: yes
                plugin_stargazers_charts: yes
                plugin_stargazers_charts_type: classic
                plugin_stargazers_days: 14
